#!/usr/bin/env node
/**
 * App identity for Android, generated from the SVG sources in `assets-src/` (docs/RELEASE.md §App identity).
 *
 *   node scripts/gen-icons.mjs            writes into android/app/src/main/res
 *   node scripts/gen-icons.mjs --preview <file.png>   also writes a contact sheet for review
 *
 * Sources (the art director edits these; rerun the script and commit the PNGs):
 *   assets-src/icon-background.svg   adaptive icon background layer, 108 dp
 *   assets-src/icon-foreground.svg   adaptive icon foreground layer, 108 dp, 66 dp safe circle
 *   assets-src/icon-monochrome.svg   Android 13 themed icon, one colour
 *
 * Outputs
 *   mipmap-{m..xxxh}dpi/ic_launcher_{foreground,background,monochrome}.png   adaptive layers (108 dp)
 *   mipmap-{m..xxxh}dpi/ic_launcher.png, ic_launcher_round.png               legacy icons, API 24–25 (48 dp)
 *   mipmap-anydpi-v26/ic_launcher.xml, ic_launcher_round.xml                 adaptive icon XML
 *   drawable-{m..xxxh}dpi/splash_icon.png      Android 12+ splash icon (288 dp canvas, art inside the 192 dp circle)
 *   drawable/splash.xml                        API 24–30 window background: sea gradient + splash_icon
 *                                              (a layer-list, so no full-screen bitmaps in the APK)
 *
 * Renders with headless Chromium from PLAYWRIGHT_BROWSERS_PATH (/opt/pw-browsers); never `playwright install`.
 */
import { chromium } from '@playwright/test';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const app = join(dirname(fileURLToPath(import.meta.url)), '..');
const res = join(app, 'android/app/src/main/res');
const src = (f) => readFileSync(join(app, 'assets-src', f), 'utf8');
const dataUri = (svg) => `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;

const BG = dataUri(src('icon-background.svg'));
const FG = dataUri(src('icon-foreground.svg'));
const MONO = dataUri(src('icon-monochrome.svg'));
/** Splash backdrop behind the art (THEME.palette.bg). Also windowSplashScreenBackground in styles.xml. */
const SPLASH_BG = '#0B1020';

const DENSITIES = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };

/** One HTML page per image; `body` is absolutely positioned layers in a w×h box. */
function page(w, h, body, background = 'transparent') {
  return `<!doctype html><html><head><style>
    html,body{margin:0;width:${w}px;height:${h}px;background:${background};overflow:hidden}
    .l{position:absolute;display:block}
  </style></head><body>${body}</body></html>`;
}
const img = (uri, x, y, w, h, extra = '') => `<img class="l" src="${uri}" style="left:${x}px;top:${y}px;width:${w}px;height:${h}px;${extra}">`;

const jobs = [];
for (const [d, s] of Object.entries(DENSITIES)) {
  const layer = Math.round(108 * s);
  const mip = join(res, `mipmap-${d}`);
  jobs.push({ file: join(mip, 'ic_launcher_foreground.png'), w: layer, h: layer, html: page(layer, layer, img(FG, 0, 0, layer, layer)) });
  jobs.push({ file: join(mip, 'ic_launcher_background.png'), w: layer, h: layer, html: page(layer, layer, img(BG, 0, 0, layer, layer)) });
  jobs.push({ file: join(mip, 'ic_launcher_monochrome.png'), w: layer, h: layer, html: page(layer, layer, img(MONO, 0, 0, layer, layer)) });

  // Legacy (API 24–25): 48 dp, art on a 44 dp shape with 2 dp margin, layers scaled so the
  // 72 dp adaptive viewport fills the shape (what an adaptive launcher would show).
  const size = Math.round(48 * s);
  const shape = Math.round(44 * s);
  const off = (size - shape) / 2;
  const layers = (shape * 108) / 72;
  const lo = off - (layers - shape) / 2;
  const legacy = (radius) =>
    page(
      size,
      size,
      `<div class="l" style="left:${off}px;top:${off}px;width:${shape}px;height:${shape}px;border-radius:${radius};overflow:hidden">` +
        img(BG, lo - off, lo - off, layers, layers) +
        img(FG, lo - off, lo - off, layers, layers) +
        `</div>`,
    );
  jobs.push({ file: join(mip, 'ic_launcher.png'), w: size, h: size, html: legacy('22%') });
  jobs.push({ file: join(mip, 'ic_launcher_round.png'), w: size, h: size, html: legacy('50%') });

  // Android 12+ splash icon without icon background: 288 dp canvas, art must fit a 192 dp circle.
  // The foreground's 66 dp safe circle is scaled to 176 dp.
  const sp = Math.round(288 * s);
  const fgSize = Math.round((176 / 66) * 108 * s);
  const fo = (sp - fgSize) / 2;
  jobs.push({ file: join(res, `drawable-${d}`, 'splash_icon.png'), w: sp, h: sp, html: page(sp, sp, img(FG, fo, fo, fgSize, fgSize)) });
}

const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen-icons.mjs from assets-src/*.svg. Do not edit by hand. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_background"/>
    <foreground android:drawable="@mipmap/ic_launcher_foreground"/>
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
</adaptive-icon>
`;

/** API 24–30 splash (the launch theme's android:background). Colours: THEME.palette bgGlow → bg. */
const splashXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/gen-icons.mjs. Do not edit by hand. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle">
            <gradient
                android:type="radial"
                android:centerX="0.5"
                android:centerY="0.46"
                android:gradientRadius="420dp"
                android:startColor="#FF132043"
                android:endColor="${SPLASH_BG.replace('#', '#FF')}" />
        </shape>
    </item>
    <item>
        <bitmap android:gravity="center" android:src="@drawable/splash_icon" />
    </item>
</layer-list>
`;

const browser = await chromium.launch();
try {
  const ctx = await browser.newContext({ deviceScaleFactor: 1 });
  const p = await ctx.newPage();
  for (const j of jobs) {
    await p.setViewportSize({ width: j.w, height: j.h });
    await p.setContent(j.html);
    await p.evaluate(() => Promise.all([...document.images].map((i) => i.decode())));
    mkdirSync(dirname(j.file), { recursive: true });
    writeFileSync(j.file, await p.screenshot({ omitBackground: true, clip: { x: 0, y: 0, width: j.w, height: j.h } }));
  }
  writeFileSync(join(res, 'drawable', 'splash.xml'), splashXml);
  for (const f of ['ic_launcher.xml', 'ic_launcher_round.xml']) {
    mkdirSync(join(res, 'mipmap-anydpi-v26'), { recursive: true });
    writeFileSync(join(res, 'mipmap-anydpi-v26', f), adaptive);
  }

  // Optional review sheet: layers, launcher mask shapes with the safe circle, splash.
  const pi = process.argv.indexOf('--preview');
  if (pi > 0) {
    const out = process.argv[pi + 1];
    const cell = (label, inner) =>
      `<div style="display:inline-block;margin:12px;text-align:center;font:12px sans-serif;color:#EAF2FF;vertical-align:top">${inner}<div>${label}</div></div>`;
    const masked = (r, sz = 144) =>
      `<div style="position:relative;width:${sz}px;height:${sz}px;border-radius:${r};overflow:hidden">${img(BG, -sz / 4, -sz / 4, sz * 1.5, sz * 1.5)}${img(FG, -sz / 4, -sz / 4, sz * 1.5, sz * 1.5)}</div>`;
    const safe = `<div style="position:relative;width:216px;height:216px">${img(BG, 0, 0, 216, 216)}${img(FG, 0, 0, 216, 216)}<div class="l" style="left:42px;top:42px;width:132px;height:132px;border:1px dashed #FF5FA2;border-radius:50%;box-sizing:border-box"></div></div>`;
    const html = page(
      1100,
      560,
      cell('layers + 66 dp safe circle', safe) +
        cell('circle', masked('50%')) +
        cell('squircle', masked('30%')) +
        cell('square', masked('8%')) +
        cell('themed (tinted)', `<div style="width:144px;height:144px;border-radius:50%;background:#D8E6FF;overflow:hidden;position:relative">${img(MONO, -36, -36, 216, 216, 'filter:brightness(0) saturate(100%) invert(18%) sepia(40%) saturate(900%) hue-rotate(190deg)')}</div>`) +
        '<br>' +
        cell('Android 12+ splash', `<div style="width:220px;height:390px;background:${SPLASH_BG};position:relative">${img(FG, 110 - 72, 195 - 72, 144, 144)}</div>`) +
        cell('API 24–30 splash', `<div style="width:220px;height:390px;background:radial-gradient(circle 250px at 50% 46%, #132043, ${SPLASH_BG});position:relative">${img(FG, 110 - 72, 195 - 72, 144, 144)}</div>`) +
        cell('legacy 48 dp ×3', `<img src="file://${join(res, 'mipmap-xxxhdpi', 'ic_launcher.png')}" style="width:144px"> <img src="file://${join(res, 'mipmap-xxxhdpi', 'ic_launcher_round.png')}" style="width:144px">`),
      '#1d2433',
    );
    const f = join(dirname(out), '_preview.html');
    writeFileSync(f, html);
    await p.setViewportSize({ width: 1100, height: 560 });
    await p.goto(`file://${f}`);
    await p.evaluate(() => Promise.all([...document.images].map((i) => i.decode())));
    await p.screenshot({ path: out });
  }
} finally {
  await browser.close();
}
console.log(`gen-icons: ${jobs.length} PNGs, 2 adaptive icon XML and drawable/splash.xml in ${res}`);
